"""
PR worker for async Pull Request generation.

This worker handles:
- Transforming DOM patches to code changes
- Creating GitHub branches and PRs
- Sending notifications
"""

import logging
from datetime import datetime

from src.models.experiment import Experiment
from src.models.variant import Variant
from src.models.site import Site
from src.models.pull_request import PullRequest, PRStatus
from src.models.user import User
from src.services.llm_service import llm_service
from src.integrations.github import create_github_client
from src.integrations.resend import resend_client
from src.config import settings

logger = logging.getLogger(__name__)


async def generate_pr_for_experiment(pr_id: str) -> bool:
    """
    Generate a Pull Request for an experiment's winning variant.

    Args:
        pr_id: ID of the PullRequest document

    Returns:
        True if PR was created successfully
    """
    logger.info(f"Generating PR {pr_id}")

    pr = await PullRequest.get(pr_id)
    if not pr:
        logger.error(f"PR {pr_id} not found")
        return False

    try:
        # Get related documents
        experiment = await Experiment.get(pr.experiment_id)
        variant = await Variant.get(pr.variant_id)
        site = await Site.get(pr.site_id)

        if not all([experiment, variant, site]):
            raise ValueError("Missing experiment, variant, or site")

        if not site.github_repo or not site.github_pat:
            raise ValueError("GitHub repo or PAT not configured for site")

        # Get user for notification
        user = await User.get(experiment.created_by)

        # Transform patches to code
        logger.info("Transforming patches to code changes")
        transform_response = await llm_service.transform_patches_to_code(
            patches=[p.model_dump() for p in variant.patches],
            html=experiment.base_html_snapshot or "",
        )

        # Create GitHub client
        github = create_github_client(site.github_pat)

        # Create branch
        logger.info(f"Creating branch: {pr.branch_name}")
        await github.create_branch(site.github_repo, pr.branch_name)

        # Apply code changes
        for change in transform_response.changes:
            logger.info(f"Applying change to: {change.file_path}")

            # Get current file content
            existing = await github.get_file_content(
                site.github_repo,
                change.file_path,
                pr.branch_name,
            )

            if existing:
                content, sha = existing
                # Replace original code with modified code
                new_content = content.replace(change.original_code, change.modified_code)

                if new_content != content:
                    await github.create_or_update_file(
                        site.github_repo,
                        change.file_path,
                        new_content,
                        f"Apply UX improvement: {change.explanation}",
                        pr.branch_name,
                        sha,
                    )
            else:
                # File doesn't exist, create it
                await github.create_or_update_file(
                    site.github_repo,
                    change.file_path,
                    change.modified_code,
                    f"Add UX improvement: {change.explanation}",
                    pr.branch_name,
                )

        # Create Pull Request
        logger.info("Creating Pull Request")
        pr_body = f"""## Summary

{transform_response.pr_description}

## Changes

This PR implements the winning variant from experiment **{experiment.name}**.

### Variant: {variant.name}

{variant.description or 'No description provided.'}

---

*Generated by [Pulse UX Optimizer](https://pulse-ux.com)*
"""

        github_pr = await github.create_pull_request(
            site.github_repo,
            transform_response.pr_title,
            pr_body,
            pr.branch_name,
        )

        # Update PR document
        pr.status = PRStatus.CREATED
        pr.github_pr_number = github_pr["number"]
        pr.github_pr_url = github_pr["html_url"]
        pr.code_changes = {
            "changes": [c.model_dump() for c in transform_response.changes]
        }
        await pr.save()

        # Send notification
        if user and user.email:
            try:
                await resend_client.send_pr_created(
                    to=user.email,
                    experiment_name=experiment.name,
                    pr_url=github_pr["html_url"],
                    pr_number=github_pr["number"],
                )
            except Exception as e:
                logger.warning(f"Failed to send PR notification: {e}")

        await github.close()
        logger.info(f"PR created successfully: {github_pr['html_url']}")
        return True

    except Exception as e:
        logger.error(f"Failed to generate PR {pr_id}: {e}")

        # Update PR status
        pr.status = PRStatus.FAILED
        pr.error_message = str(e)
        await pr.save()

        return False
