"""
LLM service for UX variant generation and code transformation.

This service orchestrates Claude Opus 4.5 calls via OpenRouter for:
- Generating UX improvement variants from HTML
- Transforming DOM patches into source code changes
"""

from pydantic import BaseModel, Field

from src.integrations.openrouter import openrouter_client
from src.models.variant import PatchAction


class GeneratedPatch(BaseModel):
    """A single DOM patch generated by the LLM."""

    action: str = Field(..., description="Patch action type")
    selector: str = Field(..., description="CSS selector for the target element")
    value: str = Field(..., description="Value to apply")
    property_name: str | None = Field(None, description="Property name for style/attribute actions")
    reasoning: str = Field(..., description="Why this change improves UX")


class GeneratedVariant(BaseModel):
    """A complete variant generated by the LLM."""

    name: str = Field(..., description="Short descriptive name for the variant")
    description: str = Field(..., description="Description of what this variant changes")
    patches: list[GeneratedPatch] = Field(..., description="List of DOM patches to apply")


class VariantGenerationResponse(BaseModel):
    """Response containing multiple generated variants."""

    variants: list[GeneratedVariant] = Field(..., description="List of generated variants")
    analysis: str = Field(..., description="Overall analysis of the page and opportunities")


class CodeChange(BaseModel):
    """A single code change for PR generation."""

    file_path: str = Field(..., description="Path to the file to modify")
    original_code: str = Field(..., description="Original code snippet to find")
    modified_code: str = Field(..., description="Modified code to replace with")
    explanation: str = Field(..., description="Explanation of the change")


class CodeTransformationResponse(BaseModel):
    """Response containing code changes for a variant."""

    changes: list[CodeChange] = Field(..., description="List of code changes")
    pr_title: str = Field(..., description="Suggested PR title")
    pr_description: str = Field(..., description="Detailed PR description")


class LLMService:
    """Service for LLM-powered UX optimization."""

    async def generate_variants(
        self,
        html: str,
        target_url: str,
        optimization_goal: str | None = None,
        num_variants: int = 2,
    ) -> VariantGenerationResponse:
        """
        Generate UX improvement variants from HTML.

        Args:
            html: HTML content of the page
            target_url: URL of the page being optimized
            optimization_goal: What to optimize for (e.g., "increase signups")
            num_variants: Number of variants to generate

        Returns:
            VariantGenerationResponse with generated variants
        """
        goal = optimization_goal or "improve conversions and user engagement"

        # Truncate HTML if too long
        max_html_length = 50000
        if len(html) > max_html_length:
            html = html[:max_html_length] + "\n<!-- HTML truncated -->"

        prompt = f"""Analyze this webpage and generate {num_variants} UX improvement variants.

URL: {target_url}
Optimization Goal: {goal}

HTML Content:
```html
{html}
```

Generate variants that:
1. Make meaningful UX improvements likely to increase conversions
2. Use valid CSS selectors that will reliably target elements
3. Focus on high-impact changes (CTAs, headlines, forms, trust signals)
4. Are different from each other (don't just vary colors)

Available patch actions:
- style: Modify CSS properties (requires property_name)
- class_add: Add CSS classes
- class_remove: Remove CSS classes
- attribute: Set/modify HTML attributes (requires property_name)
- text: Change text content
- html: Replace innerHTML (use sparingly)
- hide: Hide element (display: none)
- show: Show element

For each variant, provide:
- A descriptive name (e.g., "Bold CTA with Urgency")
- A description of what it changes and why
- Specific DOM patches with valid CSS selectors

Generate {num_variants} distinct variants plus an overall analysis."""

        response = await openrouter_client.chat_completion_structured(
            messages=[{"role": "user", "content": prompt}],
            response_model=VariantGenerationResponse,
            temperature=0.7,
            max_tokens=4096,
        )

        return response

    async def transform_patches_to_code(
        self,
        patches: list[dict],
        html: str,
        repo_structure: str | None = None,
    ) -> CodeTransformationResponse:
        """
        Transform DOM patches into source code changes.

        Args:
            patches: List of DOM patches from the winning variant
            html: Original HTML of the page
            repo_structure: Optional description of repository structure

        Returns:
            CodeTransformationResponse with code changes
        """
        patches_json = "\n".join(
            f"- {p['action']}: selector='{p['selector']}', value='{p['value']}'"
            + (f", property='{p.get('property_name')}'" if p.get('property_name') else "")
            for p in patches
        )

        prompt = f"""Convert these DOM patches into source code changes for a Pull Request.

DOM Patches:
{patches_json}

Original HTML (for context):
```html
{html[:10000]}
```

{f"Repository Structure: {repo_structure}" if repo_structure else ""}

For each patch, determine:
1. Which source file needs to be modified (e.g., component file, CSS file, template)
2. What the original code looks like
3. What the modified code should be
4. A clear explanation of the change

If you can't determine the exact source file, use reasonable assumptions based on common frameworks (React, Vue, Next.js, etc.).

Generate a PR title and description that clearly explains the UX improvements."""

        response = await openrouter_client.chat_completion_structured(
            messages=[{"role": "user", "content": prompt}],
            response_model=CodeTransformationResponse,
            temperature=0.3,
            max_tokens=4096,
        )

        return response

    async def generate_comparison_analysis(
        self,
        control_description: str,
        variants: list[dict],
    ) -> str:
        """
        Generate AI analysis comparing variants.

        Args:
            control_description: Description of the control (original)
            variants: List of variant data with names, descriptions, and metrics

        Returns:
            Analysis text comparing the variants
        """
        variants_text = "\n".join(
            f"- {v['name']}: {v['description']} "
            f"(Impressions: {v.get('impressions', 0)}, Conversions: {v.get('conversions', 0)})"
            for v in variants
        )

        prompt = f"""Analyze these A/B test variants and provide insights:

Control: {control_description}

Variants:
{variants_text}

Provide a brief analysis (2-3 sentences) covering:
1. Key differences between variants
2. Which variant shows the most promise and why
3. Any recommendations for the user

Be concise and actionable."""

        response = await openrouter_client.chat_completion(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=500,
        )

        return response


# Singleton instance
llm_service = LLMService()
