"""
LLM service for UX variant generation and code transformation.

This service orchestrates Claude Opus 4.5 calls via OpenRouter for:
- Generating UX improvement variants from HTML
- Transforming DOM patches into source code changes
"""

from pydantic import BaseModel, Field

from src.integrations.openrouter import openrouter_client
from src.models.variant import PatchAction


class GeneratedPatch(BaseModel):
    """A single DOM patch generated by the LLM."""

    action: str = Field(..., description="Patch action type")
    selector: str = Field(..., description="CSS selector for the target element")
    value: str = Field(..., description="Value to apply")
    property_name: str | None = Field(None, description="Property name for style/attribute actions")
    reasoning: str = Field(..., description="Why this change improves UX")


class GeneratedVariant(BaseModel):
    """A complete variant generated by the LLM."""

    name: str = Field(..., description="Short descriptive name for the variant")
    description: str = Field(..., description="Description of what this variant changes")
    patches: list[GeneratedPatch] = Field(..., description="List of DOM patches to apply")


class VariantGenerationResponse(BaseModel):
    """Response containing multiple generated variants."""

    variants: list[GeneratedVariant] = Field(..., description="List of generated variants")
    analysis: str = Field(..., description="Overall analysis of the page and opportunities")
    email_subject: str = Field(..., description="Subject line for the notification email to the user")
    email_body: str = Field(..., description="HTML body content for the notification email (just the inner content, no <html> wrapper)")


class CodeChange(BaseModel):
    """A single code change for PR generation."""

    file_path: str = Field(..., description="Path to the file to modify")
    original_code: str = Field(..., description="Original code snippet to find")
    modified_code: str = Field(..., description="Modified code to replace with")
    explanation: str = Field(..., description="Explanation of the change")


class CodeTransformationResponse(BaseModel):
    """Response containing code changes for a variant."""

    changes: list[CodeChange] = Field(..., description="List of code changes")
    pr_title: str = Field(..., description="Suggested PR title")
    pr_description: str = Field(..., description="Detailed PR description")


class LLMService:
    """Service for LLM-powered UX optimization."""

    async def generate_variants(
        self,
        html: str,
        target_url: str,
        optimization_goal: str | None = None,
        num_variants: int = 2,
        screenshot_url: str | None = None,
        css: str | None = None,
    ) -> VariantGenerationResponse:
        """
        Generate UX improvement variants from HTML.

        Args:
            html: HTML content of the page
            target_url: URL of the page being optimized
            optimization_goal: What to optimize for (e.g., "increase signups")
            num_variants: Number of variants to generate
            screenshot_url: Optional URL of a screenshot for vision-based analysis
            css: Optional CSS content for styling context

        Returns:
            VariantGenerationResponse with generated variants
        """
        goal = optimization_goal or "improve conversions and user engagement"

        # Truncate HTML if too long
        max_html_length = 40000
        if len(html) > max_html_length:
            html = html[:max_html_length] + "\n<!-- HTML truncated -->"

        # Truncate CSS if too long
        css_section = ""
        if css:
            max_css_length = 15000
            if len(css) > max_css_length:
                css = css[:max_css_length] + "\n/* CSS truncated */"
            css_section = f"""
CSS Stylesheets (IMPORTANT - understand the site's theme from this):
```css
{css}
```

NOTE: This site uses a DARK THEME. Pay attention to the color scheme, background colors (likely dark grays/blacks),
and text colors (likely light/white). Any styling changes MUST maintain this dark theme aesthetic.
"""

        # Add vision context to prompt if screenshot is available
        vision_note = ""
        if screenshot_url:
            vision_note = """
IMPORTANT: I'm providing you with a screenshot of the actual page. Use this visual context
to understand the current design, layout, colors, and visual hierarchy. Make your suggestions
based on what you SEE in the screenshot, not just the HTML structure.
"""

        prompt = f"""Analyze this webpage and generate {num_variants} UX improvement variants.
{vision_note}
URL: {target_url}
Optimization Goal: {goal}
{css_section}
HTML Content:
```html
{html}
```

CRITICAL: Generate variants with DRAMATIC, VISUALLY OBVIOUS differences that are immediately noticeable.
Each variant should look significantly different from the control at first glance.

Generate variants that:
1. Make BOLD, HIGH-IMPACT visual changes (not subtle tweaks)
2. Use contrasting colors, larger sizes, different layouts
3. Focus on the most prominent elements: main headlines, primary CTAs, hero sections
4. Each variant should be DRAMATICALLY different from the control and from each other

EXAMPLES OF DRAMATIC CHANGES (use these as inspiration):
- Change button colors to high-contrast colors (bright green, orange, red)
- Make CTAs 1.5x-2x larger with bold borders
- Add eye-catching backgrounds or gradients
- Transform flat buttons into 3D/elevated designs
- Add urgency text like "Limited Time" or "Act Now"
- Increase headline font sizes by 20-40%
- Add animated elements or pulsing effects
- Change layout orientation (horizontal to vertical or vice versa)

Available patch actions:
- style: Modify CSS properties (requires property_name) - USE THIS FOR VISUAL CHANGES
- class_add: Add CSS classes
- class_remove: Remove CSS classes
- attribute: Set/modify HTML attributes (requires property_name)
- text: Change text content - USE THIS FOR COMPELLING COPY
- html: Replace innerHTML (use sparingly, never on interactive elements)
- hide: Hide element (display: none) - ONLY for non-functional decorative elements
- show: Show element

IMPORTANT CONSTRAINTS:
- Do NOT use 'hide' action on interactive elements (dropdowns, forms, buttons)
- Only hide purely decorative elements that don't affect functionality
- Maintain dark theme if the site uses one (check CSS above)

For each variant, provide:
- A descriptive name indicating the change (e.g., "Giant Green CTA" or "Urgent Red Hero")
- A brief description (1-2 sentences max)
- 3-6 specific DOM patches with DRAMATIC visual impact
- Keep reasoning brief (1 sentence per patch)

Also generate a personalized email notification for the user:
- Subject: A catchy, exciting subject line about the new experiment (e.g., "Experiment Ready: 20% more clicks?")
- Body: A friendly, professional message explaining the core optimization strategy. Use HTML tags (<p>, <strong>, <ul>) but NO <html>/<body> wrappers. Mention specific improvements.

Generate {num_variants} distinct variants plus a brief (2-3 sentence) analysis."""

        response = await openrouter_client.chat_completion_structured(
            messages=[{"role": "user", "content": prompt}],
            response_model=VariantGenerationResponse,
            temperature=0.7,
            max_tokens=8192,
            image_url=screenshot_url,
        )

        return response

    async def transform_patches_to_code(
        self,
        patches: list[dict],
        html: str,
        repo_structure: str | None = None,
    ) -> CodeTransformationResponse:
        """
        Transform DOM patches into source code changes.

        Args:
            patches: List of DOM patches from the winning variant
            html: Original HTML of the page
            repo_structure: Optional description of repository structure

        Returns:
            CodeTransformationResponse with code changes
        """
        patches_json = "\n".join(
            f"- {p['action']}: selector='{p['selector']}', value='{p['value']}'"
            + (f", property='{p.get('property_name')}'" if p.get('property_name') else "")
            for p in patches
        )

        prompt = f"""Convert these DOM patches into source code changes for a Pull Request.

DOM Patches:
{patches_json}

Original HTML (for context):
```html
{html[:10000]}
```

{f"Repository Structure: {repo_structure}" if repo_structure else ""}

For each patch, determine:
1. Which source file needs to be modified (e.g., component file, CSS file, template)
2. What the original code looks like
3. What the modified code should be
4. A clear explanation of the change

If you can't determine the exact source file, use reasonable assumptions based on common frameworks (React, Vue, Next.js, etc.).

Generate a PR title and description that clearly explains the UX improvements."""

        response = await openrouter_client.chat_completion_structured(
            messages=[{"role": "user", "content": prompt}],
            response_model=CodeTransformationResponse,
            temperature=0.3,
            max_tokens=4096,
        )

        return response

    async def generate_comparison_analysis(
        self,
        control_description: str,
        variants: list[dict],
    ) -> str:
        """
        Generate AI analysis comparing variants.

        Args:
            control_description: Description of the control (original)
            variants: List of variant data with names, descriptions, and metrics

        Returns:
            Analysis text comparing the variants
        """
        variants_text = "\n".join(
            f"- {v['name']}: {v['description']} "
            f"(Impressions: {v.get('impressions', 0)}, Conversions: {v.get('conversions', 0)})"
            for v in variants
        )

        prompt = f"""Analyze these A/B test variants and provide insights:

Control: {control_description}

Variants:
{variants_text}

Provide a brief analysis (2-3 sentences) covering:
1. Key differences between variants
2. Which variant shows the most promise and why
3. Any recommendations for the user

Be concise and actionable."""

        response = await openrouter_client.chat_completion(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=500,
        )

        return response


# Singleton instance
llm_service = LLMService()
